numpy array


In [14]:
import numpy as np
first = [1,2,43,67,13,44,99]
print(first) #!D array



[1, 2, 43, 67, 13, 44, 99]


In [15]:
print("1D array ")
a=np.array([1,2,3,4,5])
print(a)

1D array 
[1 2 3 4 5]


In [16]:
print("2D array")
b=np.array([[1,2,4,5],
            [2,4,8,6]])
print(b)

2D array
[[1 2 4 5]
 [2 4 8 6]]


In [17]:
print("3D array")
c=np.array([[[2,1,4,6,7],
             [4,1,8,9,6],
             [11,2,4,3,1]]])
print(c)

3D array
[[[ 2  1  4  6  7]
  [ 4  1  8  9  6]
  [11  2  4  3  1]]]


In [18]:
print(a.size)
print(b.size)
print(c.size)

5
8
15


In [19]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 4)
(1, 3, 5)


In [20]:
d=np.array([[[2,1.4,4.3,6,7],
             [4,1,8,9.8,6],
             [11,2.5,4,3,1.6]]])
print(d.dtype)

float64


In [21]:
e=np.array([[[2,1,4,6,7],
             [4,1,8,9,6],
             [11,2,4,3,1]]])
print(e.dtype)

int64


Task 

In [ ]:
t1=[2,4,6,8]
t2=[1,3,5,7]
print(np.add(t1, t2)) # we calculated summation of two matrix 

[ 3  7 11 15]


In [24]:
trans=[[1,2,4,7,3],
       [3,4,1,8,5]]
print(np.transpose(trans))

[[1 3]
 [2 4]
 [4 1]
 [7 8]
 [3 5]]
