In [1]:
import numpy as np


In [ ]:
x= np.ones(6)
print(x) #printed as a float

[1. 1. 1. 1. 1. 1.]


In [ ]:
x = np.ones((6),dtype=int)
print(x) #printed as a integer

[1 1 1 1 1 1]


In [ ]:
z= np.zeros((4,8),dtype = int)
z            #first number ,4 is row and second number,8 is colum
             #we can also write only the varible to print the array instead of writing print()

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
a=np.arange(1,21)
a #print(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
b=np.arange(1,21,2)
b #printing only odd numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [18]:
c = np.arange(2, 21, 2)
c = c.reshape((2, 5))
c


array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

TASK

In [20]:
t1=np.arange(0,18)
t1_1=t1.reshape((6,3))
t2=np.arange(20,38)
t2_2=t2.reshape((6,3))
print(np.add(t1_1,t2_2))


[[20 22 24]
 [26 28 30]
 [32 34 36]
 [38 40 42]
 [44 46 48]
 [50 52 54]]


In [1]:
import pandas as pd


In [2]:
pd.DataFrame({"Yes": [50,21,78] , "No": [121 , 2 ,45]})

Yes   No
0   50  121
1   21    2
2   78   45

In [4]:
pd.Series([2,3,5,8,9,11])

0     2
1     3
2     5
3     8
4     9
5    11
dtype: int64